stack: bvberkum/drone-github
version: 0.0.3
description: |
  Drone is a Continuous Delivery platform built on Docker (github:bvberkum/x-kontena-stacks)
variables:
  loadbalancer:
    type: string
    from:
      env: LOADBALANCER
      service_link:
        prompt: Choose a loadbalancer
        image: kontena/lb
  drone_host:
    type: string
    from:
      prompt: Drone hostname
  agent_instances:
    type: integer
    default: 1
    from:
      prompt: Number of Drone agents
  gh_client_id:
    type: string
    from:
      env: GITHUB_CLIENT
      vault: ${STACK}-gh-client
      prompt: GitHub client id
    to:
      vault: ${STACK}-gh-client
  gh_client_secret:
    type: string
    from:
      env: GITHUB_SECRET
      vault: ${STACK}-gh-secret
      prompt: GitHub secret
    to:
      vault: ${STACK}-gh-secret
  admins:
    type: string
    required: false
    from:
      prompt: Comma separated list of admin users
  organizations:
    type: string
    required: false
    from:
      prompt: Comma separated list of approved organizations
  shared_secret:
    type: string
    from:
      env: SECRET
      vault: ${STACK}-secret
      random_string: 24
    to:
      vault: ${STACK}-secret
services:
  server:
    image: drone/drone:0.7
    instances: 1
    stateful: true
    mem_limit: 64m
    environment:
      - DRONE_DEBUG=true
      - DRONE_GITHUB=true
      - DRONE_OPEN=true
      # {% if admins %}
      - DRONE_ADMIN={{ admins }}
      # {% endif %}
      # {% if organizations %}
      - DRONE_ORGS={{ organizations }}
      # {% endif %}
      - DRONE_HOST=https://{{ drone_host }}
      - KONTENA_LB_INTERNAL_PORT=8000
      - KONTENA_LB_VIRTUAL_HOSTS={{ drone_host }}
    secrets:
      - secret: ${STACK}-gh-client
        name: DRONE_GITHUB_CLIENT
        type: env
      - secret: ${STACK}-gh-secret
        name: DRONE_GITHUB_SECRET
        type: env
      - secret: ${STACK}-secret
        name: DRONE_AGENT_SECRET
        type: env
    volumes:
      - /var/lib/drone
    links:
      - "{{ loadbalancer }}"

  agent:
    image: drone/drone:0.7
    command: agent
    instances: {{ agent_instances }}
    mem_limit: 64m
    depends_on:
      - server
    environment:
      - DRONE_SERVER=ws://server:8000/ws/broker
      - DOCKER_API_VERSION=1.24
    secrets:
      - secret: ${STACK}-secret
        name: DRONE_SECRET
        type: env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
